import prisma from '../../../config/db';
import { Portfolio, PortfolioProject, PortfolioCertificate, PortfolioAnalytics } from '@prisma/client';
import { CreatePortfolioInput, UpdatePortfolioInput } from '../validators/portfolio.validator';

export const portfolioRepository = {
  // Create a new portfolio
  async create(data: CreatePortfolioInput, studentId: string) {
    return prisma.portfolio.create({
      data: {
        ...data,
        studentId,
        slug: data.slug,
        visibility: data.visibility ?? 'PUBLIC',
      },
    });
  },

  // Retrieve a portfolio by slug or ID
  async getById(id: string) {
    return prisma.portfolio.findUnique({
      where: { id },
      include: {
        projects: true,
        certificates: true,
        analytics: true,
      },
    });
  },

  async getBySlug(slug: string) {
    return prisma.portfolio.findUnique({
      where: { slug },
      include: {
        projects: true,
        certificates: true,
        analytics: true,
      },
    });
  },

  // Update existing portfolio
  async update(id: string, data: UpdatePortfolioInput) {
    return prisma.portfolio.update({
      where: { id },
      data,
    });
  },

  // Delete portfolio
  async delete(id: string) {
    return prisma.portfolio.delete({
      where: { id },
    });
  },

  // Add a project to portfolio
  async addProject(portfolioId: string, projectId: string, role?: string, description?: string) {
    return prisma.portfolioProject.create({
      data: {
        portfolioId,
        projectId,
        role,
        description,
      },
    });
  },

  // Add a certificate to portfolio
  async addCertificate(portfolioId: string, certificateId: string, displayOrder?: number) {
    return prisma.portfolioCertificate.create({
      data: {
        portfolioId,
        certificateId,
        displayOrder,
      },
    });
  },

  // Fetch analytics (placeholder, real analytics generated by job)
  async getAnalytics(portfolioId: string) {
    return prisma.portfolioAnalytics.findUnique({
      where: { portfolioId },
    });
  },
};
